### ISSUE TITLE
My Address and  Overview in My Account is inaccessible

### ISSUE THREAD

**Issue by crhistianramirez** [aviabird/angularspree#132]
I took a look at the route configuration and it looks like they're both set to redirect to `/orders` so perhaps this is intentional?

```
 {
    path: '',
    component: UserComponent,
    children: [
      { path: '', redirectTo: 'orders' },
      { path: 'overview', component: OverviewComponent, redirectTo: 'orders' },
      { path: 'orders', component: OrdersComponent },
      { path: 'orders/detail/:number', component: OrderDetailComponent },
      { path: 'addresses', component: AddressesComponent, redirectTo: 'orders' }
    ]
  }
```

**Comment by crhistianramirez** [comment]
Should've looked just a little bit more closely, I can see these are just placeholders. I don't think it'd be a bad idea to just put some text there that says addresses under construction or something similar, otherwise it just looks like the links are broken

**Comment by pkrawat1** [comment]
Thanks @crhistianramirez. I agree with you.
We are already working on develop branch on `adding/updating` all the coming soon `features/placeholders/redirects`.
I'll update the master branch asa develop is stable.

**Comment by pkrawat1** [comment]
Closing this as for now. We have started working on the version 1.0, where all the of these will be fixed. Currently its in pre-alpha version.
