### ISSUE TITLE
Unable to run project

### ISSUE THREAD

**Issue by akshaypsingh** [aviabird/angularspree#250]
I am unable to run the project.
Is it possible to have video for this project.

**Comment by pkrawat1** [comment]
@akshaypsingh Did you follow this https://github.com/aviabird/angularspree/wiki/Installation-Guide

**Comment by akshaypsingh** [comment]
Yes..

**Comment by rafaeltejero** [comment]
What error do you get?

**Comment by pkrawat1** [comment]
@akshaypsingh  Can you provide a detailed description with screenshot about the error you get.

**Comment by smartcoder23** [comment]
I am getting this error.. 

![screenshot from 2018-10-22 12-53-50](https://user-images.githubusercontent.com/35736555/47285190-b2f02d80-d607-11e8-8f5c-b9b89e89cf47.png)

**Comment by pkrawat1** [comment]
no reply so closing
