### ISSUE TITLE
ngu-carousel code update

### ISSUE THREAD

**Issue by BadiuAlexandru** [aviabird/angularspree#258]
You upgraded the ngu-carousel plugin but you forgot to update the code.

This works for me 

`<ngu-carousel #landingBanners [inputs]="carouselOne" (onMove)="onMoveBanner($event)" [dataSource]="bannerItems">
  <ngu-tile *nguCarouselDef="let banner;" class="bannerStyle">
    <a href="{{banner.link_url}}">
      <img src={{banner.image_link}} alt="" style="display: block; width: 100%;">
    </a>
  </ngu-tile>
  <button NguCarouselPrev class='leftRs'></button>
  <button NguCarouselNext class='rightRs'></button>
</ngu-carousel>`

` public carouselOne: NguCarouselConfig;`

`this.carouselOne = {
      grid: { xs: 1, sm: 1, md: 1, lg: 1, all: 0 },
      slide: 1,
      speed: 400,
      interval: { timing: 4000 },
      point: {
        visible: true,
        //pointStyles: '.ngucarouselPoint {}' //  <-- this is not available anymore
      },
      load: 2,
      touch: true,
      loop: true,
      custom: 'banner'
    };`

**Comment by mzerbo98** [comment]
@BadiuAlexandru. Thanks, your solution worked for me. Could you also send the product-image correction please ?

**Comment by chandraupendra** [comment]
> You upgraded the ngu-carousel plugin but you forgot to update the code.
> 
> This works for me
> 
> `<ngu-carousel #landingBanners [inputs]="carouselOne" (onMove)="onMoveBanner($event)" [dataSource]="bannerItems"> <ngu-tile *nguCarouselDef="let banner;" class="bannerStyle"> <a href="{{banner.link_url}}"> <img src={{banner.image_link}} alt="" style="display: block; width: 100%;"> </a> </ngu-tile> <button NguCarouselPrev class='leftRs'></button> <button NguCarouselNext class='rightRs'></button> </ngu-carousel>`
> 
> ` public carouselOne: NguCarouselConfig;`
> 
> `this.carouselOne = { grid: { xs: 1, sm: 1, md: 1, lg: 1, all: 0 }, slide: 1, speed: 400, interval: { timing: 4000 }, point: { visible: true, //pointStyles: '.ngucarouselPoint {}' // <-- this is not available anymore }, load: 2, touch: true, loop: true, custom: 'banner' };`

there is a problem with interval key

**Comment by pkrawat1** [comment]
Fixed in #299
