### ISSUE TITLE
Issue while running project

### ISSUE THREAD

**Issue by rhtvma** [aviabird/angularspree#266]
I followed the information provided here for running this project on my local machine.
https://github.com/aviabird/angularspree/wiki/Installation-Guide.

I am getting below mentioned issue :

**At the time of installation using yarn:**
![image](https://user-images.githubusercontent.com/11902919/46192411-961e4e00-c318-11e8-8815-195c11b40bf8.png)

**At the time of running :**

![image](https://user-images.githubusercontent.com/11902919/46192481-db428000-c318-11e8-80cf-9f210335a757.png)

**Comment by mdsabz** [comment]
Downloaded a copy, while we try to run the command ng serve, encounter the same problem. Any resolution towards this?
