### ISSUE TITLE
Error while serving the application 

### ISSUE THREAD

**Issue by trugosoft** [aviabird/angularspree#280]
Hi all,

I am getting following issue when i try to serve the application.

![image](https://user-images.githubusercontent.com/39978653/46717924-34020900-cc87-11e8-9f01-e3c6d18e9641.png)

Is this something wrong with configuration ?

I am using Windows 10 

Regards
Sathya

**Comment by pkrawat1** [comment]
Hi @trugosoft , try same on `spree` branch.

**Comment by pkrawat1** [comment]
can you delete your node_modules and install fresh packages in `spree` breanch?

**Comment by trugosoft** [comment]
Dear @pkrawat1 , its working fine thanks 

Regards
Sathya
