### ISSUE TITLE
Issue while running the application 

### ISSUE THREAD

**Issue by aditya2905** [aviabird/angularspree#284]
![image](https://user-images.githubusercontent.com/34435785/46933587-48247c80-d072-11e8-8bd6-94d8bf1f268a.png)

**Comment by gopalshimpi** [comment]
@aditya2905 please refer https://github.com/aviabird/angularspree/issues/280 for this one.

**Comment by jahangirhussain** [comment]
can you please tell us shortly what is spree...how to use it after downloading this folder from git I  am sorry but I am a layman..?

**Comment by jahangirhussain** [comment]
and can we run only its front ?without downloading and configuring its back end. so that we can write by our own API with MySQL type database

**Comment by gopalshimpi** [comment]
@jahangirhussain I already mentioned that `spree` branch works on `angularspree-api` and `master` branch works on `Aviacommerce-API`. So don't need to write separate API for it. If you don't want to clone & configure API simply use  `prodApiEndpoint: 'https://ngspree-api.herokuapp.com/' in default.ts

Then run `yarn start:dev-ng-spree`

**Comment by jahangirhussain** [comment]
alright,what about a link which has given at avia backend installation page named avia ecommerce.is there any difference between to download any of them...angularspree of avia..??

**Comment by jahangirhussain** [comment]
> @jahangirhussain I already mentioned that `spree` branch works on `angularspree-api` and `master` branch works on `Aviacommerce-API`. So don't need to write separate API for it. If you don't want to clone & configure API simply use `prodApiEndpoint: 'https://ngspree-api.herokuapp.com/' in default.ts
> 
> Then run `yarn start:dev-ng-spree`

alright,what about a link which has given at avia backend installation page named avia ecommerce.is there any difference between to download any of them...angularspree of avia..??...if I am not wrong aviacommerce-API is one which has named as avia commerce like this.Is it or I am in wrong way? or if I have to download angularspree-api to integrate with spree frontend what is the procedure if its integration of front end.
![image](https://user-images.githubusercontent.com/43291957/47095622-0567cd80-d247-11e8-87b1-31f5b6302e31.png)
