### ISSUE TITLE
Unable to run the project

### ISSUE THREAD

**Issue by smartcoder23** [aviabird/angularspree#291]
![screenshot from 2018-10-22 12-53-50](https://user-images.githubusercontent.com/35736555/47281896-b92bdd00-d5fa-11e8-8b05-98b027f4fffa.png)

**Comment by BeerendraMC** [comment]
Yeah, I'm also facing the same issue!

**Comment by pkrawat1** [comment]
@smartcoder23 @BeerendraMC Try using `spree` branch for now. We'll fix this.

**Comment by pkrawat1** [comment]
Fixed in master branch now. So closing
