### ISSUE TITLE
export 'DropdownModule' was not found in 'ng2-bootstrap/dropdown'

### ISSUE THREAD

**Issue by yogee412** [aviabird/angularspree#47]
When I run ng serve I'm getting this error saying export 'DropdownModule' was not found in 'ng2-bootstrap/dropdown' and I don't know how to fix this.

WARNING in ./src/app/shared/index.ts
39:12-26 "export 'DropdownModule' was not found in 'ng2-bootstrap/dropdown'

WARNING in ./src/app/shared/index.ts
50:12-26 "export 'DropdownModule' was not found in 'ng2-bootstrap/dropdown'

ERROR in /Users/Yitao/Documents/myProject/angularspree/src/app/shared/index.ts (11,10): Module '"/Users/Yitao/Documents/myProject/angularspree/
node_modules/ng2-bootstrap/dropdown/index"' has no exported member 'DropdownModule'.

ERROR in Error encountered resolving symbol values statically. Calling function 'DropdownModule', function calls are not supported. Consider re
placing the function or lambda with a reference to an exported function, resolving symbol SharedModule in /Users/Yitao/Documents/myProject/angu
larspree/src/app/shared/index.ts, resolving symbol SharedModule in /Users/Yitao/Documents/myProject/angularspree/src/app/shared/index.ts

**Comment by pkrawat1** [comment]
Hi @yogee412 

You might have upgraded version of ng2-bootstrap, plus @angular2 version. Please check that the current angular2 version is at 4.0.0 and ng2-bootstrap at 1.4.2 .

I was getting this error right after trying to upgrade both of these.

**Comment by yogee412** [comment]
Hi @pkrawat1 
Thanks for your response.
I'm using the exact package.json file checked out from master branch.
  "dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^2.0.0",
    "@ngrx/store": "^2.2.1",
    "bootstrap": "^3.3.7",
    "bootstrap-sass": "^3.3.7",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "immutable": "^3.8.1",
    "ng2-bootstrap": "^1.4.0",
    "reselect": "^2.5.4",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  }

**Comment by pkrawat1** [comment]
can you show the package json for ng2-bootstrap

it should show be something like this
{
  "main": "bundles/ng2-bootstrap.umd.js",
  "version": "1.4.2",
 ...
}

**Comment by pkrawat1** [comment]
Also you could run 

`yarn` to install using yarn.lock If not done

**Comment by yogee412** [comment]
After I update ng2-bootstrap to 1.4.2, the problem is fixed!
Thanks for your help @pkrawat1  :)

**Comment by pkrawat1** [comment]
That's awesome. @yogee412
