### ISSUE TITLE
the website demo does not work on IE 11

### ISSUE THREAD

**Issue by phuhien92** [aviabird/angularspree#55]
I tested the website on IE Edge and 11 version. It does not work on IE 11

**Comment by arjun289** [comment]
@ashish173
Getting the following error in the console. 
SCRIPT5007: Unable to get property 'apply' of undefined or null reference
vendor.886af24f0be20ee2cae3.bundle.js (1,440154)

**Comment by ashish173** [comment]
@phuhien92 Thanks for reporting it, @arjun289 Thanks for helping us narrow it down with the error log. We'll fix this asap.

**Comment by gaurav848** [comment]
Hey, i tried to run this app locally but getting Webpack exception.
Steps is tried : Downloaded Zip file, unzipped in a folder on windows 10, Open folder in VS Code, Run npm install, It created node_module folder, Ran "ng serve" command, and then it threw below webpack not found exception:
C:\XXXX\angularspree-master> ng serve
Cannot find module 'webpack'
Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)

I added "webpack": "2.5.1", in package.json, but then it gave another exception like :
ng serve
Cannot destructure property `createHash` of 'undefined' or 'null'.
TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.
    at Object.<anonymous> 

Can you please suggest if i am doing something wrong or missed any step?

**Comment by pkrawat1** [comment]
@gaurav848 

## Try these steps
- git  clone
- yarn install
- yarn start:dev-ng-spree `To start default theme`

**Comment by gaurav848** [comment]
Hey @pkrawat1 ,  Thank you so much for providing me the steps to run it locally. 
Today i tried running these and it ran good till the step 2.
but when i ran 3rd step i.e. "yarn start:dev-ng-spree" , it started on port 4200 but on loading it on browser, it resulted in following custom module exception. Please suggest.

> ERROR in src/environments/environment.dev-custom.ts(1,31): error TS2307: Cannot find module './../config/custom'.
> src/environments/environment.prod-custom.ts(1,31): error TS2307: Cannot find module '../config/custom'.

Error detail: 
PS C:\RnD\AngularSpree-Git\angularspree> yarn start:dev-ng-spree
yarn run v1.7.0
$ ng serve --configuration=dev-ng-spree
** Angular Live Development Server is listening on localhost: 4200, open your browser on http://localhost:4200/ **

Date: 2018-07-02T19:25:04.682Z
Hash: 3e469ef88baaa30c8e73
Time: 13161ms
chunk {main} main.js, main.js.map (main) 1.95 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 693 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.4 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 268 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 325 kB [initial] [rendered]

ERROR in src/environments/environment.dev-custom.ts(1,31): error TS2307: Cannot find module './../config/custom'.
src/environments/environment.prod-custom.ts(1,31): error TS2307: Cannot find module '../config/custom'.

**Comment by gaurav848** [comment]
Hey @pkrawat1 , It is working fine now. Apologies, i should have looked on the error detail more carefully, i commented content in environment.dev-custom.ts and environment.prod-custom.ts to make it compile properly and then it came up on browser. I understand these file are for customizing it.  thanks for the project.

**Comment by pkrawat1** [comment]
@phuhien92  we have done recent UI related changes. Feel free to comment if it still breaking in IE.
