### ISSUE TITLE
Signup form validations

### ISSUE THREAD

**Issue by mpvineesh** [aviabird/angularspree#61]
In sign up form, as of now only validating whether the fields are empty or not. Apart from this we can implement some more validations like email type, mobile - number validations etc? Also the mobile number field is of type number which shows a counter icon. This we can remove.
![capture](https://user-images.githubusercontent.com/12124458/29565453-9f892592-8763-11e7-8bad-8ac8f0eed5c5.PNG)

**Comment by ashish173** [comment]
@mpvineesh yes we should, please feel free to send a PR for this one.

**Comment by mpvineesh** [comment]
I have already created a pull request https://github.com/aviabird/angularspree/pull/60

**Comment by ashish173** [comment]
@mpvineesh oops, I didn't know that. Let me check please assign the PR's to me or any one of the contributors in future. @pkrawat1 @kartikjagdale @zeus999

**Comment by mpvineesh** [comment]
yeah sure, I will do that in future. Please review the code changes and let me know if it follows the coding standards and rules so that I can make required changes if any.

**Comment by ashish173** [comment]
I think we can close this issue as it has been resolved. thanks @mpvineesh
