### ISSUE TITLE
Add to cart

### ISSUE THREAD

**Issue by jomarbarnobal** [aviabird/angularspree#64]
add to cart from home getting NAN

**Comment by ashish173** [comment]
@kartikjagdale @zeus999 can you please verify this, please flush the DB if that's the problem.

**Comment by kartikjagdale** [comment]
it was a heroku usage limit surpassed issue.
I have flushed the db.
closing the ticket.

**Comment by ashish173** [comment]
@jomarbarnobal Thanks for reporting 👍

**Comment by jomarbarnobal** [comment]
Thanks
