### ISSUE TITLE
When will it have Angular Universal support for better SEO?

### ISSUE THREAD

**Issue by hb-github** [aviabird/angularspree#65]
Hey guys,
Great work!

when can we expect this SEO support in this app? I am eager to use this code in one of my projects.

Cheers!

**Comment by pkrawat1** [comment]
Will have to see if Ruby on rails has any Angular universal support.

**Comment by pkrawat1** [comment]
@hb-github We have integrated angular universal recently. You can check pacakage.json for commands.
