### ISSUE TITLE
SEO improvement: schema.org / json-LD support

### ISSUE THREAD

**Issue by tycho01** [aviabird/angularspree#66]
It seems that unlike the traditional Spree frontend, AngularSpree is still missing support for [schema.org](http://schema.org/), used by Google and others to generate rich snippets based on this semantic markup. It'd be cool to see this make it in here as well.

**Comment by pkrawat1** [comment]
- [ ] Add Microdata for where required.

**Comment by pkrawat1** [comment]
We have added json-LD config for product pages. Thanks for mentioning that.
