### ISSUE TITLE
Adding AlertService for failed requests

### ISSUE THREAD

**Issue by arp95** [aviabird/angularspree#70]
In case of backend errors or any other reasons for failed http requests we should add an alert service to display the client of the error faced.

**Comment by ashish173** [comment]
@arp95 Thanks for the suggestion! would like to work on it?

**Comment by arp95** [comment]
yes can i work on it?

**Comment by ashish173** [comment]
Yes, please go ahead! 

I would recommend joining our slack channel(link in the readme) there we can have better discussions related to the development and we can also add you to our project management board.
