### ISSUE TITLE
Update to Angular version 5.0.0

### ISSUE THREAD

**Issue by bergben** [aviabird/angularspree#72]
Hey there,

is there an update to Angular version 5.0.0. lined up? And what is the general state of the project if I may ask? It seems like the "What's coming soon" part is lined up since quite some months...

Keep up the great work :)

**Comment by ashish173** [comment]
@bergben Thanks for your kind words! It means a lot!

Yes, we'll be updating to the latest version(5.0.0) by 15th Nov.

Regarding your "What's coming soon" part?

Firstly, We are working on the SEO aspect pretty actively, using angular universal server-side rendering.

Secondly, Mobile responsive views are in pipeline after 15th, along with wishlist implementation.

Hope that helps!

**Comment by bergben** [comment]
Thanks for the info @ashish173, it does help a lot. Thanks for your efforts.

**Comment by roman-ziablov** [comment]
Hi,
Update to Angular version 5.0.0?

**Comment by arjun289** [comment]
Hi @roman-ziablov, I am working on the task to update it to Angular version 5.0. It would be available by middle of the next week.

**Comment by oktay-alizada** [comment]
Hi everyone.
Are there any news about this enhancement?
Thank you :)

**Comment by kartikjagdale** [comment]
hi @oktay-alizada Unfortunately since last two months we didn't had much time to work on this. (lot of client tasks in queue :smile:), However now as this issue has again come to light, I think we will have a small internal discussion and assign it to someone who is free this week.
Thank you for asking for the update. :smile: 
Stay tuned.
cc: @ashish173

**Comment by oktay-alizada** [comment]
Hi,
@kartikjagdale  thank you very much, will wait for it

**Comment by pkrawat1** [comment]
Updated to angular 5 and ngrx store 4

**Comment by oktay-alizada** [comment]
Thank you very much :)
