### ISSUE TITLE
Website very unfriendly on Mobile

### ISSUE THREAD

**Issue by sidcool1234** [aviabird/angularspree#75]
I tested the demo app on Android Chrome browser and it's not very usable.  It's slow, laggy and quite ugly.

**Comment by zeus999** [comment]
@sidcool1234 thanks for raising this issue, we are currently working and migarting it to bootstrap 4 and you will get the update very soon.

**Comment by imballa** [comment]
Hello, We still can't get any update..

**Comment by pkrawat1** [comment]
@sidcool1234  @imballa New UI is in progress in `develop` branch.
