### ISSUE TITLE
Full page is not Loading now.

### ISSUE THREAD

**Issue by amitlodhi** [aviabird/angularspree#76]
I think you have changed the repository so Your page has so many errors. That's why this project is not loaded fully. Kindly check your Demo page.

**Comment by pkrawat1** [comment]
Api end point is fixed now.
Thanks

**Comment by amitlodhi** [comment]
Ya. Fixed on Demo. But I am using your project via clone, it's has the same
error in my localhost. Kindly commit on github also. So I can able to use
your project.

**Comment by pkrawat1** [comment]
@amitlodhi replace api in environment.ts to this `https://damp-anchorage-69261.herokuapp.com`

**Comment by amitlodhi** [comment]
It works. Thank you
