### ISSUE TITLE
While add item to cart in place of count NaN is coming in Navbar

### ISSUE THREAD

**Issue by nmanikiran** [aviabird/angularspree#82]
this is happening when the server call fails / out of stock / No Quantity 
API : https://damp-anchorage-69261.herokuapp.com/spree/api/v1/orders/R100827806/line_items?order_token=KnBfCyNeXdhjUOltn-vBNw1513854377595
error :
`{
    "exception": "Validation failed: Quantity selected of \"Ruby on Rails Tote\" is not available."
}`

it would be better if we show a toast message 

![image](https://user-images.githubusercontent.com/3726349/34253574-3553d3ba-e66e-11e7-85d9-8223abda0462.png)

**Comment by pkrawat1** [comment]
This is fixed in alpha version 1.0.0-alpha
